spring:
  profiles:
    active: local
  application:
    name: demo
  data:
    mongodb:
      uri: mongodb://test:test12!!@localhost:27017/test?maxPoolSize=500&waitQueueMultiple=20&waitQueueTimeoutMS=10000

